development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: thinginator_development
  pool: 5
  username: paul
  password: appleg3

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: thinginator_test
  pool: 5
  username: paul
  password: appleg3

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: thinginator_production
#   pool: 5
#   username: thinginator
#   password:
